[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nifty_quant_terminal"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "flet>=0.24.0",
    "yfinance",
    "pandas",
    "requests",
    "numpy",
    "multitasking",
    "peewee",
    "beautifulsoup4"
]

[tool.flet.app]
path = "main.py"
product = "Nifty Pro Quant Terminal"
company = "Quant"
