name: Build Nifty APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Libraries
        run: pip install flet requests

      - name: Build APK (Flet Engine)
        run: echo "y" | flet build apk
        
      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: NiftyPro-Mobile-App
          path: "*/.apk"
